### ISSUE TITLE
set_bounds error

### ISSUE THREAD

**Issue by mzhen77** [facebookresearch/nevergrad#1267]
## Steps to reproduce

``` python
instrum = ng.p.Instrumentation(ng.p.Scalar().set_bounds(lower=0.5, upper=2.5))
optimizer = ng.optimizers.NGOpt(parametrization=instrum, budget=100)
recommendation = optimizer.minimize(lambda x: (x - 1.) ** 2)
```

## Observed Results

``` python
ValueError: Only data between [0.5] and [2.5] can be transformed back.
Got: [0.]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/Projects/playground/nevergrad/boundary_error.py", line 3, in <module>
    instrum = ng.p.Instrumentation(ng.p.Scalar().set_bounds(lower=0.5, upper=2.5))
  File "C:\Users\mzhen\anaconda3\envs\fmu\lib\site-packages\nevergrad\parametrization\data.py", line 223, in set_bounds
    layer(self, inplace=True)
  File "C:\Users\mzhen\anaconda3\envs\fmu\lib\site-packages\nevergrad\parametrization\_datalayers.py", line 94, in __call__
    raise errors.NevergradValueError(
nevergrad.common.errors.NevergradValueError: Current value is not within bounds, please update it first
```

## Expected Results

  * Should not be the error

## Relevant Code

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by mzhen77** [comment]
It seems the code way has to be:

``` python
instrum = ng.p.Instrumentation(ng.p.Scalar(init=1.1).set_bounds(lower=0.5, upper=2.5))
optimizer = ng.optimizers.NGOpt(parametrization=instrum, budget=100)
recommendation = optimizer.minimize(lambda x: (x - 1.) ** 2)
```
