### ISSUE TITLE
Issue with certain optimizers (scipy maybe)?

### ISSUE THREAD

**Issue by rawrses** [facebookresearch/nevergrad#180]
## Steps to reproduce

1. Install nevergrad on ubuntu 18.04 , python 3.6.7 (Also seen using anaconda on Red Hat 6.2, python 3.6.8)
2.  Ask and tell with particular optimizers (seen so far with Cobyla, Powell, maybe just the scipy ones)

## Observed Results

Script does not terminate properly, requires Ctrl+C. 
 ```
^CException ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
 ```

## Expected Results

Optimizer (Cobyla) should close normally. Also, if I stop the messaging thread the code terminates, but I still get the following message: 
capi_return is NULL
Call-back cb_calcfc_in__cobyla__user__routines failed.

which might be related to scipy, not sure. Regardless, I don't think I should have to go in and kill the thread. 

## Relevant Code

Bit redundant with the print statements, but here: 
 ```
from nevergrad.optimization import optimizerlib
from nevergrad.optimization import registry
from nevergrad.optimization.recaster import _MessagingThread as mt
import threading

def beale2(p):
    x,y = p[0],p[1]
    return (1.5-x+x*y)**2+(2.25-x+x*(y**2))**2+(2.625-x+x*(y**3))**2

print('Initial Threading')
print(threading.enumerate())
a = registry['OnePlusOne'](2,budget=500)
print('Threading after getting 1+1')
print(threading.enumerate())

print('Threading after each step: ')
for i in range(3):
    x = a.ask()
    a.tell(x,beale2(*x.args))
    print(threading.enumerate())

print('Threading after getting Cobyla')
print(threading.enumerate())
b = registry['Cobyla'](2,budget=5)
print('Threading after each step: ')
for i in range(5):
    x = b.ask()
    b.tell(x,beale2(*x.args))
    print(threading.enumerate())
print('Done. Current threads: ')
print(threading.enumerate())
for t in reversed(threading.enumerate()):
    if type(t)==type(mt(None)):
        pass
        #t.stop() 
    else:
        pass
print('Final.')
print(threading.enumerate())  
```

**Comment by jrapin** [comment]
Hi,
Thanks for pointing out. I will investigate futher as soon as I have time (but that may not happen before a week or more :s)
Also, I already ran into a similar issue, when scipy optimizer just hangs, which makes the main thread hang as well, and it seems difficult to identify this, so I do not know if there will be an easy fix :s It may also be some error that is not properly caught, I'll need to have a closer look.

**Comment by jrapin** [comment]
I try the script:
- I did not experiment any hanging
- the thread is only stopped when the optimizer is deleted (`del b`) which I think is the simplest behavior (the underlying scipy optimizer may still be running, and it is therefore possible to increase the budget of the optimizer and resume the optimization... although this is a bit hacky...).
- the error message comes from stopping COBYLA, I'll try to hide it (but it serves me as a reminder that it those optimizers are horribly hacky :s)

Does the script you sent freezes everytime you run it? which version of nevergrad and scipy are you using? And which OS?

**Comment by rawrses** [comment]
Hm....okay. Yeah I realize now there is a certain amount of special manipulation to get those optimizers to work like the other ones. 

The script does freeze everytime I run it, unless I stop the messaging thread. I am running 0.2.0 nevergrad, and 1.2.1 scipy. I am just running out of terminal on ubuntu 18.04, though I also tested it on a remote server which has Red Hat 6.2 running and has anaconda.

**Comment by jrapin** [comment]
I have the same config and still not any freeze :s Which version of Python maybe?
I'll be happy to get rid of all this hack but could not find any nicer way :s if you have any idea in mind, let me know :s

**Comment by teytaud** [comment]
I get the same problem, and @brockho as well. 
On Macos.

**Comment by brockho** [comment]
Just to clarify: I did *not* experience this problem on my own laptop (Windows with Anaconda python and the most recent Nevergrad version). However, when we looked at it together with @teytaud on Monday, I saw it happening on his computer.

**Comment by ZhiyanWXZ** [comment]
I get the same problem too, on TX2.

**Comment by jrapin** [comment]
> I get the same problem too, on TX2.

Hi,
Can you try to explicitely delete the optimizer instance (`del optimizer`) and tell me if it still freezes? Some optimizers (mostly scipy based) require to start a thread, which can prevent the exit if they are not garbage collected :s
