### ISSUE TITLE
ufunc 'isnan' not supported for the input types..

### ISSUE THREAD

**Issue by shoegazerstella** [facebookresearch/nevergrad#26]
I am trying the example provided in this [issue](https://github.com/facebookresearch/nevergrad/issues/1#issuecomment-449134639).
I am just doing a simple trial with variable epochs and all the rest of the parameters set their default values.

``` 
epoch = instru.variables.OrderedDiscrete([10, 20, 30, 40, 50, 60, 70, 80])
 ifunc = instru.InstrumentedFunction(train_supervised,
                                    input=FILE_TRAIN,
                                    label='__label__',
                                    thread=12,
                                    epoch=epoch) 
```

but the code stops here with an error that I did not manage to solve:

``` 
python3.6 train.py 
ifunc.dimension: 1
OPTIMIZER Instance of TwoPointsDE(dimension=1, budget=100, num_workers=1)
Read 0M words
Number of words:  93768
Number of labels: 13
Progress: 100.0% words/sec/thread:  164210 lr:  0.000000 loss:  0.160289 ETA:   0h 0m
Traceback (most recent call last):
  File "train.py", line 158, in <module>
    train_opt(FILE_TRAIN)
  File "train.py", line 139, in train_opt
    recommendation = optimizer.optimize(ifunc)
  File "/usr/local/lib/python3.6/dist-packages/nevergrad/optimization/base.py", line 237, in optimize
    self.tell(x, job.result())
  File "/usr/local/lib/python3.6/dist-packages/nevergrad/optimization/base.py", line 118, in tell
    if np.isnan(value) or value == np.inf:
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe'' 
```

I have installed nevergrad with pip and I am using python3.6.
I am sure I do not have NANs in my data, and as you can see, the `train_supervised` method is working fine, something happens after this.

**Comment by jrapin** [comment]
Actually, this may indeed be the problem. I had not checked the return type in the issue you mentioned, but `train_supervised` seems to return a tuple. You will need to wrap it to return only the value to *minimize* (not maximize).

**Comment by shoegazerstella** [comment]
Hi @jrapin, thanks for the prompt response and help.
So, the function `train_supervised` is the custom fastText classification function and it outputs a fastText model:

```
model: <fastText.FastText._FastText object at 0x7f21b550b7b8>
type: <class 'fastText.FastText._FastText'> 
```
 as you can see [here](https://github.com/facebookresearch/fastText/blob/master/python/fastText/FastText.py)

How to handle this for the optimization to work?

Also, my example is slightly different from the one you posted above. I am doing:
```
optim.optimize(ifunc)
```
instead of
```
optim.optimize(myfunction)
```

If I try your latest implementation, I get the following:

```
  File "train.py", line 166, in <module>
    train_opt(FILE_TRAIN)
  File "train.py", line 137, in train_opt
    optim.optimize(train_supervised)
  File "/usr/local/lib/python3.6/dist-packages/nevergrad/optimization/base.py", line 223, in optimize
    runnings.append((x, executor.submit(objective_function, x)))
  File "/usr/local/lib/python3.6/dist-packages/nevergrad/optimization/utils.py", line 144, in submit
    return FinishedJob(function(*args, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/fasttext-0.8.22-py3.6-linux-x86_64.egg/fastText/FastText.py", line 357, in train_supervised
    a = _build_args(locals())
  File "/usr/local/lib/python3.6/dist-packages/fasttext-0.8.22-py3.6-linux-x86_64.egg/fastText/FastText.py", line 304, in _build_args
    setattr(a, k, v)
TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (self: fasttext_pybind.args, arg0: str) -> None

Invoked with: <fasttext_pybind.args object at 0x7fa92807f378>, (-0.2138988285067873,)
```

**Comment by jrapin** [comment]
I am not familiar with fasttext, but looking at issue #1 I would say that something like this should work:
```
def objective_function(*args, **kwargs):
    model = train_supervised(*args, **kwargs)
    samples_number, precision, recall = model.test(FILE_VALID, k=1)
    return -precision

epoch = instru.variables.OrderedDiscrete([10, 20, 30, 40, 50, 60, 70, 80])
 ifunc = instru.InstrumentedFunction(objective_function,
                                     input=FILE_TRAIN,
                                     label='__label__',
                                     thread=12,
                                     epoch=epoch)
```

The key here is to build the objective function, which takes your arguments as input and returns a loss (which will be minimized).

**Comment by shoegazerstella** [comment]
Thanks a lot! This is working. :)
I was wrongly defining my `objective_function`. 
I am closing the issue then.
