### ISSUE TITLE
Update pytorch version when TLS issue is solved

### ISSUE THREAD

**Issue by jrapin** [facebookresearch/nevergrad#305]
We observe incompatibility between pytorch 1.3.0 and sklearn:
```
(venv) circleci@95c3075fe681:~/repo$ python -m nevergrad.functions.rl.test_envs
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/circleci/repo/nevergrad/functions/rl/__init__.py", line 7, in <module>
    from . import agents
  File "/home/circleci/repo/nevergrad/functions/rl/agents.py", line 12, in <module>
    import torch
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: dlopen: cannot load any more object with static TLS
```

A fix on pytorch may be coming:
https://github.com/pytorch/pytorch/pull/28536

In the meantime version of pytorch is `<1.3.0` (from #307)

**Comment by jrapin** [comment]
Solved by #391
