### ISSUE TITLE
nosetests fail with 93 errors, e.g. "ValueError: high is out of bounds for int32"

### ISSUE THREAD

**Issue by claforte** [facebookresearch/nevergrad#36]
## Steps to reproduce

  1. `git clone https://github.com/claforte/nevergrad.git`
  2. `cd nevergrad`
  3. `python setup.py develop`
  4. `nosetests nevergrad`

I reproduced the issue on 2 different PCs running Windows 10, recent versions of anaconda, python 3.6.6. One environment has lots of packages (e.g. pytorch 0.4), while the other only contains nevergrad and its dependencies:

  1. `conda create --name test python=3.6.6`
  2. `conda activate test`
  3. `conda install -c anaconda numpy` (otherwise `python setup.py develop` fails due to missing numpy)
  4. continue to step 3 of the *reproduction steps* above.

## Observed Results

  * 93 tests failed, the vast majority report the same error:
```
======================================================================
ERROR: nevergrad.optimization.test_sequences.test_rescaler_on_hammersley
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\deepr\lib\site-packages\nose-1.3.7-py3.6.egg\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "D:\cl\amd_code\dl\nevergrad\nevergrad\optimization\test_sequences.py", line 78, in test_rescaler_on_hammersley
    sampler = sequences.ScrHammersleySampler(dimension=3, budget=4)
  File "D:\cl\amd_code\dl\nevergrad\nevergrad\optimization\sequences.py", line 176, in __init__
    super().__init__(dimension, budget, scrambling=True)
  File "D:\cl\amd_code\dl\nevergrad\nevergrad\optimization\sequences.py", line 165, in __init__
    super().__init__(dimension-1, budget, scrambling)
  File "D:\cl\amd_code\dl\nevergrad\nevergrad\optimization\sequences.py", line 134, in __init__
    self.permgen = HaltonPermutationGenerator(dimension, scrambling)
  File "D:\cl\amd_code\dl\nevergrad\nevergrad\optimization\sequences.py", line 118, in __init__
    self.seed = np.random.randint(np.iinfo(np.uint32).max)
  File "mtrand.pyx", line 991, in mtrand.RandomState.randint
ValueError: high is out of bounds for int32

----------------------------------------------------------------------
Ran 335 tests in 21.589s

FAILED (SKIP=1, errors=93)
```

I tried to attach a complete log produced using `nosetests nevergrad > nosetests_error.txt 2>&1`, but I wasn't able to drag-and-drop it on this issue. I will try again once it's been submitted.

While some tests fail, the examples in the README run successfully, and I was able to use the library with my own code.

## Expected Results

  * What did you expect to happen?

All tests to pass, or a mention of which tests are known to fail (e.g. in the README).

Note: I'm not an expert in pip and anaconda, it's very possible I'm doing something wrong. I just wanted to get clarification before I spend more time debugging this issue:
- What exact latest versions of Python, numpy are you using?
- Do all tests run successfully?
- Any advice?

## Relevant Code

n/a

**Comment by claforte** [comment]
Full error log:

[nosetests_error.txt](https://github.com/facebookresearch/nevergrad/files/2753508/nosetests_error.txt)

**Comment by jrapin** [comment]
Could not reproduce even with the steps.
Does that help though ? #38

**Comment by claforte** [comment]
pip freeze:
```bayesian-optimization==1.0.0
certifi==2018.10.15
cma==2.6.0
coverage==5.0a4
cycler==0.10.0
genty==1.3.2
joblib==0.13.1
kiwisolver==1.0.1
matplotlib==3.0.2
mkl-fft==1.0.6
mkl-random==1.0.1
mypy==0.650
mypy-extensions==0.4.1
-e git+https://github.com/claforte/nevergrad.git@a06ae7ccf312392a7de4e90f93084834a5a978f0#egg=nevergrad
nose==1.3.7
nose-timer==0.7.4
numpy==1.15.4
pandas==0.24.0rc1
pyparsing==2.3.0
python-dateutil==2.7.5
pytz==2018.9
scikit-learn==0.20.2
scipy==1.2.0
six==1.12.0
typed-ast==1.1.1
typing-extensions==3.7.2
wincertstore==0.2```

**Comment by claforte** [comment]
Thank Jérémy, I will try #38 and let you know either way.

**Comment by jrapin** [comment]
Not the latest `numpy` version then (1.6.0). Anyway, since I couldn't reproduce with it, that makes sense. Hopefully the patch will work, it seems better to me at least

**Comment by claforte** [comment]
I ran it on your branch. There are now a lot less errors, but several types of errors remain, some of which don't have stack traces. I attached the new log:

[nosetests_error2.txt](https://github.com/facebookresearch/nevergrad/files/2755413/nosetests_error2.txt)

I have to go back to my normal project so I'm not sure I'll have time to investigate on my end, but if you want me to run a couple more test or provide more information I'll be happy to. :-)

**Comment by jrapin** [comment]
Ok,
I've slightly updated the diff for one more problem (the int32 errors, hopefully) and merged.
But some issue still remain. I still cannot reproduce any of the errors so it's a bit complicated. I suppose this is due to incompatibilities with Windows, I may need to add some continuous integration for it eventually, but probably not this week :s

One of the error you get for instance is a file that should be imported at runtime (D:\cl\amd_code\dl\nevergrad\nevergrad\benchmark\benchmark\additional\example.py), leading to KeyError: 'additional_experiment'. Can you check that it indeed exists in your installation? If yes, the importlib may be acting differently with Windows :s

**Comment by claforte** [comment]
Hi Jérémy, it's on my computer here:
`D:\cl\amd_code\dl\nevergrad\nevergrad\benchmark\additional\example.py`

... not in...
`D:\cl\amd_code\dl\nevergrad\nevergrad\benchmark\benchmark\additional\example.py` (I think you did a typo since that string isn't in the log.)

If I run this straight from the command line...
`D:\cl\amd_code\dl\nevergrad> python -m nevergrad.benchmark additional_experiment --cap_index 2 --num_workers 2 --output C:\Users\claforte\AppData\Local\Temp\tmpk53em1zv\benchmark_launch_test.csv --imports D:\cl\amd_code\dl\nevergrad\nevergrad\benchmark\additional\example.py`
... I get this error:
```
Starting repetition 1 / 1
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\test\lib\concurrent\futures\process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "D:\cl\amd_code\dl\nevergrad\nevergrad\benchmark\core.py", line 134, in compute
    for local_ind, (index, xp) in enumerate(self):
  File "D:\cl\amd_code\dl\nevergrad\nevergrad\benchmark\core.py", line 92, in __iter__
    maker = registry[self.name]
KeyError: 'additional_experiment'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\ProgramData\Anaconda3\envs\test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\cl\amd_code\dl\nevergrad\nevergrad\benchmark\__main__.py", line 94, in <module>
    repetitions=args.repetitions)
  File "D:\cl\amd_code\dl\nevergrad\nevergrad\benchmark\__main__.py", line 80, in repeated_launch
    seed=None if seed is None else seed + k)
  File "D:\cl\amd_code\dl\nevergrad\nevergrad\benchmark\__main__.py", line 28, in launch
    df = core.compute(experiment, seed=seed, cap_index=cap_index, executor=executor, num_workers=num_workers)  # type: ignore
  File "D:\cl\amd_code\dl\nevergrad\nevergrad\benchmark\core.py", line 213, in compute
    dfs = [j.result() for j in jobs]
  File "D:\cl\amd_code\dl\nevergrad\nevergrad\benchmark\core.py", line 213, in <listcomp>
    dfs = [j.result() for j in jobs]
  File "D:\ProgramData\Anaconda3\envs\test\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "D:\ProgramData\Anaconda3\envs\test\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
KeyError: 'additional_experiment'
```

I tried copying `example.py` in the same folder in case it was a Windows path problem (e.g. escaped backslashes not recognized), but it made no difference.

It's definitely finding `example.py`. If I specify the wrong filename, I get a different error:
```
(test) D:\cl\amd_code\dl\nevergrad>python -m nevergrad.benchmark additional_experiment --cap_index 2 --num_workers 2 --output benchmark_launch_test.csv --imports example2.py
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\ProgramData\Anaconda3\envs\test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\cl\amd_code\dl\nevergrad\nevergrad\benchmark\__main__.py", line 94, in <module>
    repetitions=args.repetitions)
  File "D:\cl\amd_code\dl\nevergrad\nevergrad\benchmark\__main__.py", line 74, in repeated_launch
    core.import_additional_module(path)
  File "D:\cl\amd_code\dl\nevergrad\nevergrad\benchmark\core.py", line 31, in import_additional_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'example2.py'
```

I isolate the problem, I will explain it in the next comment.

**Comment by claforte** [comment]
The problem is tied to the `num_workers 2` arguments. If I run:

`python -m nevergrad.benchmark additional_experiment --cap_index 2 --num_workers 2 --output benchmark_launch_test.csv --imports example.py`
... the problem occurs. It also takes a long time (10 seconds?) before it displays anything.

If I run instead:
`python -m nevergrad.benchmark additional_experiment --cap_index 2 --output benchmark_launch_test.csv --imports example.py`
... it runs successfully in about 1 second:

```
(test) D:\cl\amd_code\dl\nevergrad>python -m nevergrad.benchmark additional_experiment --cap_index 2 --output benchmark_launch_test.csv --imports example.py
Starting repetition 1 / 1
Starting 0: Experiment: NewOptimizer(dimension=10, budget=10, num_workers=1) on Instance of ArtificialFunction(aggregator='max', block_dimension=10, dimension=10, discrete=False, function_class='ArtificialFunction', hashing=False, name='sphere', noise_dissymmetry=False, noise_level=0, num_blocks=1, rotation=False, transform=None, translation_factor=1.0, useful_dimensions=10, useless_variables=0)
Finished 0
Starting 1: Experiment: NewOptimizer(dimension=1, budget=10, num_workers=1) on Instance of CustomFunction(dimension=1, function_class='CustomFunction', noise_level=0, offset=2, transform=None)
Finished 1
Saved data to benchmark_launch_test.csv
```

**Comment by claforte** [comment]
Incidentally, I haven't tested parallel optimization much in my own code+nevergrad so far. I'm working on a GPU-related integration and I only have one GPU on my PC to test with, so I always ask+tell 1 set of variables at a time.

Christian

**Comment by jrapin** [comment]
Hi,
Thanks a lot for investigating!
Looks like the `multithreading` package acts differently with Windows than with MacOS/Ubuntu :s
I don't have a computer running Windows so I can't test things easily (and CircleCI does not propose to run tests on Windows during continuous integration).

Either you want to investigate and I can try to guide you, or I suggest to update the title of the issue (--> "Improve Windows compatibility"?), and if someone wants to grab it and help us they will be welcome ;) (eventually, if nobody does, I'll try to find a way to make it work anyway).

**Comment by claforte** [comment]
Thanks Jeremy. Personally I don't have an immediate need for nevergrad multithreading (and multithreading triggers severe slowdown bugs in the vscode debugger on Windows). I agree with you that renaming the issue is best. I will do it.

**Comment by jrapin** [comment]
I updated the title to add that this is Windows specific (cannot reproduce on either Mac or Ubuntu).
I'll get back to it eventually.

**Comment by brockho** [comment]
Not directly related to the above issue, but also related to Windows-specific errors: #449
