### ISSUE TITLE
PSO optimizer bug

### ISSUE THREAD

**Issue by jiangwei221** [facebookresearch/nevergrad#60]
## Steps to reproduce

install pytorch1.0, and run the code, should reproduce the result
nevergrad is installed from master branch.
Once I call ```torch.from_numpy(nparray).float().to(device='cuda:1')``` or ```torch.from_numpy(nparray).float().cuda()```, it will give me assertion error.

## Observed Results

  * What happened?  This could be a description, log output, etc.

Assert error:
```
Traceback (most recent call last):
  File "bug.py", line 26, in <module>
    recommendation = optim.optimize(get_error_measurement, executor=executor)
  File "/home/jiangwei/miniconda3/envs/torch1.0/lib/python3.6/site-packages/nevergrad-0.1.1-py3.6.egg/nevergrad/optimization/base.py", line 237, in optimize
    self.tell(x, job.result())
  File "/home/jiangwei/miniconda3/envs/torch1.0/lib/python3.6/site-packages/nevergrad-0.1.1-py3.6.egg/nevergrad/optimization/base.py", line 142, in tell
    self._internal_tell(x, value)
  File "/home/jiangwei/miniconda3/envs/torch1.0/lib/python3.6/site-packages/nevergrad-0.1.1-py3.6.egg/nevergrad/optimization/optimizerlib.py", line 499, in _internal_tell
    assert x == point, str(x) + f"{x} vs {point}     {self.pop}"
AssertionError: (0.4911501931899773, -0.43302940808355883, -0.4372678287393592)(0.4911501931899773, -0.43302940808355883, -0.4372678287393592) vs (-0.3768329253449958, 0.09104643193495207, -0.10307932721079391)     [[0.5009757644092511, 0.6014841026283654, 0.6859709631240618], [0.6346080073994873, 0.7859865345869301, 0.9003882554639443], [0.7826725205681747, 0.37854971712039376, 0.6797047208048654], [0.9999999999, 0.5543576703897788, 1e-10], [0.7719219458607323, 0.42917849791820384, 1e-10], [0.7459578005791211, 1e-10, 0.9339107460996932], [0.6344706146034592, 0.9999999999, 0.5211357955736347], [0.9999999999, 0.6901278475780924, 0.39476172833171197], [0.27337963103804097, 0.24950741880316007, 0.6558451292516041], [0.4045170571446972, 0.44142018839838293, 0.8774103969720204], [0.2931404727886101, 0.4044555769698123, 0.4453981392820737], [0.5845806766378412, 0.720647952930092, 0.36691038396860787], [0.5482289873555184, 0.16233800491965578, 0.3214338601295012], [0.5442985098098989, 0.8139112813106466, 0.5338095598114053], [0.9285733747635484, 0.7721764885765621, 0.20233859057625267], [0.1717733937058818, 0.7397147758717426, 0.418468841499127], [0.47122042893368676, 0.34472409317730535, 0.15399366514420143], [1e-10, 0.3220628244980885, 0.5489131256512875], [0.16444151902631624, 0.5934854190025691, 0.5515267912162783], [0.4770005853392675, 0.42229850110668654, 0.4244852075218794], [0.34238742281461815, 0.42978664284006857, 0.8560789149377966], [0.353708077397192, 0.06932204470507108, 0.5195145124993547], [0.5780290925935871, 0.5138362412952671, 0.8322672950830423], [0.8117330114595815, 0.7950609196755931, 0.4991766093681165], [0.3531488852707311, 0.5362721515556028, 0.45895000605441877], [0.6802878404050181, 0.5851049726695651, 0.8847457111705908], [0.2469549677002738, 0.5306698658917348, 0.09330858299535116], [0.4963893894056529, 0.7295241445981984, 0.9999999999], [0.9782754185140657, 0.6190352998443717, 0.41512625078817084], [0.46593092943100056, 0.9955305520212495, 1e-10], [0.9999999999, 0.20854771969373925, 0.15305413168939158], [1e-10, 0.6313105651191179, 0.9213218538340955], [0.9019313293100729, 0.9999999999, 0.564384035404081], [0.6398750490075242, 1e-10, 0.8838234821306931], [0.36493787003029377, 0.5228582230934327, 0.7896191877081742], [0.9423521479851141, 0.8605461693648666, 0.4919352303102883], [0.5514082000961823, 0.1329081294788267, 0.23092038755143207], [0.514187105709132, 0.33944577585012803, 0.8222953832603148], [0.42020466212844065, 0.3516550689435945, 0.8303095770121608], [0.2799385916944856, 0.28369358425021557, 0.5741640442586036]]
```

## Expected Results

  * What did you expect to happen?
This code works fine when ```num_workers=10```, but doesn't work when ```num_workers=40```
Deepcopy doesn't help...
## Relevant Code

```
from concurrent import futures
import torch
import nevergrad.optimization as optimization
import numpy as np
from numpy import linalg as LA
from copy import deepcopy
import time

optim = optimization.registry['PSO'](dimension=3, budget=1000, num_workers=40)

def get_error_measurement(in_x):
    x = deepcopy(in_x)
    x = np.array(x)
    if len(x.shape) == 1:
        x = np.expand_dims(x, axis=0)
    another_mem_np = np.ones(3)
    another_mem_torch = torch.from_numpy(another_mem_np).cuda()
    estimated_error = 0
    return estimated_error

with futures.ThreadPoolExecutor(max_workers=optim.num_workers) as executor:
    recommendation = optim.optimize(get_error_measurement, executor=executor)
print(recommendation, get_error_measurement(recommendation))

```

**Comment by jiangwei221** [comment]
to reproduce the bug, you need to set the num_workers=40, and call tensor.cuda() in pytorch.

**Comment by jiangwei221** [comment]
solved using lock
```

from concurrent import futures
import torch
import nevergrad.optimization as optimization
import numpy as np
from numpy import linalg as LA
from copy import deepcopy
import time
from threading import Lock, Thread

lock = Lock()

torch.manual_seed(0)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

optim = optimization.registry['PSO'](dimension=3, budget=1000, num_workers=100)

def get_error_measurement(in_x):
    x = deepcopy(in_x)
    x = np.array(x)
    if len(x.shape) == 1:
        x = np.expand_dims(x, axis=0)
    another_mem_np = np.ones(3, dtype=np.float64)

    lock.acquire()
    another_mem_torch = torch.from_numpy(another_mem_np).float().cuda()
    lock.release()

    estimated_error = 0
    return estimated_error

with futures.ThreadPoolExecutor(max_workers=optim.num_workers) as executor:
    recommendation = optim.optimize(get_error_measurement, executor=executor)
print(recommendation, get_error_measurement(recommendation))

```

**Comment by jrapin** [comment]
Hi,
I can't dig into this right now (will probably try in the next couple of days). Do you know if the same thing happens without pytorch? I tend to feel uneasy using multithreading to submit jobs to a unique GPU device, but I am not really familiar with pytorch so I have no idea if my unease is justified or not.

**Comment by jrapin** [comment]
Actually, this is probably not even a pytorch-compatibility issue, but a PSO implementation issue. Have you tried with other optimizers (eg: TwoPointsDE, CMA, OnePlusOne)? I'll need to solve this though.

**Comment by jiangwei221** [comment]
Yes, this is a PSO problem. I tried CMA, OnePlusOne, and TwoPointsDE, they are working fine!

**Comment by jrapin** [comment]
Hi,
We found that PSO did not support the fact that "tell"s arrived in a different order than the "ask"s (while it was supposed to). It should now be solved (on master) so I am closing this issue, but don't hesitate to reopen if you still have errors ;)
