### ISSUE TITLE
Shiwa gives `ValueError: 'a' cannot be empty unless no samples are taken`

### ISSUE THREAD

**Issue by franchesoni** [facebookresearch/nevergrad#675]
## Steps to reproduce

I've tried to use Shiwa in my program but it raises an error that I could not solve by raising the budget nor the number of workers. When I use other optimizers (BO, OnePlusOne) it works fine. I could make the issue reproducible in the script below (just uncomment the desired optimizer).

The commented lines are part of my original code. The only commented lines to care about are the optimizer definitions.

## Observed Results
  * What happened?  This could be a description, log output, etc.

With optimizer OnePlusOne code runs ok. With Shiwa it doesn't and raises the following:
```
Traceback (most recent call last):
  File "/home/franchesoni/optim/evaluation/issue1.py", line 53, in <module>
    main()
  File "/home/franchesoni/optim/evaluation/issue1.py", line 13, in main
    per_r = optimize_persistence_params(dcfg, X, Y)
  File "/home/franchesoni/optim/evaluation/issue1.py", line 35, in optimize_persistence_params
    r = optimizer.minimize(persistence_fn, executor=executor, batch_mode=False)
  File "/home/franchesoni/optim/optim-venv/lib/python3.6/site-packages/nevergrad/optimization/base.py", line 479, in minimize
    args = self.ask()
  File "/home/franchesoni/optim/optim-venv/lib/python3.6/site-packages/nevergrad/optimization/base.py", line 325, in ask
    candidate = self._internal_ask_candidate()
  File "/home/franchesoni/optim/optim-venv/lib/python3.6/site-packages/nevergrad/optimization/optimizerlib.py", line 1508, in _internal_ask_candidate
    candidate = self.optims[optim_index].ask()
  File "/home/franchesoni/optim/optim-venv/lib/python3.6/site-packages/nevergrad/optimization/base.py", line 325, in ask
    candidate = self._internal_ask_candidate()
  File "/home/franchesoni/optim/optim-venv/lib/python3.6/site-packages/nevergrad/optimization/optimizerlib.py", line 1508, in _internal_ask_candidate
    candidate = self.optims[optim_index].ask()
  File "/home/franchesoni/optim/optim-venv/lib/python3.6/site-packages/nevergrad/optimization/base.py", line 325, in ask
    candidate = self._internal_ask_candidate()
  File "/home/franchesoni/optim/optim-venv/lib/python3.6/site-packages/nevergrad/optimization/optimizerlib.py", line 119, in _internal_ask_candidate
    data = func(pessimistic_data)
  File "/home/franchesoni/optim/optim-venv/lib/python3.6/site-packages/nevergrad/optimization/mutations.py", line 44, in doubledoerr_discrete_mutation
    u = self.random_state.choice(np.arange(1, max_mutations), p=p)
  File "mtrand.pyx", line 900, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken
```

## Expected Results

  * What did you expect to happen?
  Optimizer Shiwa also running ok

## Relevant Code

```python
from concurrent import futures

import nevergrad as ng

def main():
  dcfg = 0 #load_configuration()
  X, Y = 10, 20 #create_io_pairs(
    # dcfg['paths'],
    # dcfg['dataset'],
  # )

  per_r = optimize_persistence_params(dcfg, X, Y)
  print(per_r)


def optimize_persistence_params(dcfg, X, Y):
  per_params = ng.p.Dict(value_winsize=ng.p.Log(lower=1, upper=1000).set_integer_casting())
  parametrization = ng.p.Instrumentation(
    per_params, dcfg, X, Y,
  )

  # optimizer = ng.optimizers.Shiwa(
  #   parametrization=parametrization, budget=10,
  #   num_workers=1,
  # )

  # optimizer = ng.optimizers.OnePlusOne(
  #   parametrization=parametrization, budget=10,
  #   num_workers=1,
  # )

  with futures.ThreadPoolExecutor(max_workers=optimizer.num_workers) as executor:
      r = optimizer.minimize(persistence_fn, executor=executor, batch_mode=False)

  return r


def persistence_fn(per_params, dcfg, X, Y):
  # dcfg['per'] = per_params
  # algorithm = PER(dcfg)
  # per_bcurve, per_stds = batch_evaluate(algorithm, X, Y)
  # plot_bcurve(per_bcurve, per_stds, 'per')
  # per_y = np.array([float(value) for value in per_bcurve.values()])
  # score = np.mean(per_y)
  score = 0
  return score


if __name__=='__main__':
  main()
```

**Comment by franchesoni** [comment]
`>>> python -V`
Python 3.6.10
`>>> pip freeze`
bayesian-optimization==1.1.0
cma==3.0.3
cycler==0.10.0
joblib==0.14.1
kiwisolver==1.2.0
matplotlib==3.2.1
nevergrad==0.4.1
numpy==1.18.4
opencv-python-headless==4.2.0.34
pandas==1.0.3
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.1
PyYAML==5.3.1
scikit-learn==0.22.2.post1
scipy==1.4.1
six==1.14.0
timezonefinder==4.3.1
tqdm==4.46.0
typing-extensions==3.7.4.2

**Comment by jrapin** [comment]
Hi,
This is because the underlying optimizer did not support optimization in dimension 1. If you add more variables to optimize upon it should work better.
We'll work on a fix in PR #679

**Comment by teytaud** [comment]
PR on your PR @jrapin https://github.com/facebookresearch/nevergrad/pull/680

thanks for pointing out this problem @franchesoni !

**Comment by teytaud** [comment]
With 681 and 679 it should be ok.

**Comment by jrapin** [comment]
Now merged in master, @franchesoni i'm closing this, but don't hesitate to reopen, or open another issue if you experience new problems ;)
