### ISSUE TITLE
TypeError: cannot pickle '_io.TextIOWrapper' object when using ProgressBar

### ISSUE THREAD

**Issue by franchesoni** [facebookresearch/nevergrad#710]
## Steps to reproduce

  1. Make a script with multithreading optimization
  2. Add ProgressBar callback
  3. Try to pickle.dump the optimizer

## Observed Results

  * What happened?  This could be a description, log output, etc.
```
0it [00:00, ?it/s]everything is awesome, starting optimization...
 97%|██████████████████████▏| 29/30 [00:09<00:00,  1.51it/s]----------------------
----------------------
Reporting issue
Instance of NGO(parametrization=Instrumentation(Tuple(Dict(kernel=Log{int,exp=3.5495366597555704,Cl(1,2000)}),clm),Dict(X=[['ART_2018244_143036.FR', 'ART_2018244_144536.FR']],Y=[['ART_2018244_143036.FR', 'ART_2018244_144536.FR']],dcfg={'paths': {'art_dir': '/home/franchesoni/ssat01/eval/art_010x010', 'year': 2018, 'some_FR_img': '/home/franchesoni/ssat01/eval/art_010x010/C02-FR/2018/ART_2018244_160036.FR'}, 'dataset': {'vector_lenght': 2, 'max_period': 41, 'limit': 4, 'n_points': 'all', 'y_timesteps': [8], 'shuffle': True}, 'optimization': {'budget': 30, 'num_workers': 24, 'resume': False}, 'cmv': {'timestep': 10, 'value_winsize': 5, 'pyr_scale': 0.5, 'levels': 3, 'winsize': 75, 'iterations': 3, 'poly_n': 5, 'poly_sigma': 1.1, 'enabled': True}, 'per': {'kernel': 5}, 'clm': {'kernel': 45}},now_folder=2020-06-01_18:32:08.071075)), budget=30, num_workers=24)
----------------------
----------------------
Traceback (most recent call last):
  File "/home/franchesoni/ssat01/ssat02/optim/aeval/pipeline.py", line 75, in <module>
    main()
  File "/home/franchesoni/ssat01/ssat02/optim/aeval/pipeline.py", line 34, in main
    step_02(dcfg, now_folder)
  File "/home/franchesoni/ssat01/ssat02/optim/aeval/pipeline.py", line 47, in step_02
    step_0202(dcfg, now_folder)
  File "/home/franchesoni/ssat01/ssat02/optim/aeval/pipeline.py", line 67, in step_0202
    du.eout_curve_loop('clm', dcfg, now_folder, 5, 3, 3, main_process=ef.main_process,)
  File "/home/franchesoni/ssat01/ssat02/optim/aeval/utils/data_utils.py", line 374, in eout_curve_loop
    loss, val_loss = main_process(name, dcfg, now_folder, X_train, Y_train, X_val, Y_val)
  File "/home/franchesoni/ssat01/ssat02/optim/aeval/utils/evaluation_functions.py", line 206, in main_process
    r = optimize_clm_params(dcfg, X_train, Y_train, now_folder)
  File "/home/franchesoni/ssat01/ssat02/optim/aeval/utils/evaluation_functions.py", line 218, in optimize_clm_params
    return optimize_params(clm_params, 'clm', dcfg, X, Y, now_folder)
  File "/home/franchesoni/ssat01/ssat02/optim/aeval/utils/evaluation_functions.py", line 268, in optimize_params
    pickle.dump(optimizer, f)
TypeError: cannot pickle '_io.TextIOWrapper' object
100%|███████████████████████| 30/30 [00:09<00:00,  3.08it/s]
```

## Expected Results

  * What did you expect to happen?
The same that happens without the callback. Everything works fine and `pickle.dump` does not fail.

## Relevant Code

  ```
  with futures.ThreadPoolExecutor(max_workers=optimizer.num_workers) as executor:
      r = optimizer.minimize(fn, executor=executor, batch_mode=False)

  print('----------------------')
  print('----------------------')
  print('Reporting issue')
  pprint(optimizer)
  print('----------------------')
  print('----------------------')

  with open(os.path.join(
    'results', now_folder,
    f"{name}_optimizer_{str(dt.datetime.now()).replace(' ', '_')}.pkl"),
             'wb') as f:
    pickle.dump(optimizer, f)
  ```

### Optimizer definition:
```
def get_optimizer(parametrization, name, dcfg, progress):
  optimizer = ng.optimizers.NGO(
      parametrization=parametrization, budget=dcfg['optimization']['budget'],
      num_workers=dcfg['optimization']['num_workers'],
  )

  if progress:
    optimizer.register_callback("tell", ng.callbacks.ProgressBar())

  return optimizer
```
The error happens if and only if `progress = True`. The rest of the code is too long to be useful. Any ideas?
A quick googling pointed to a multiprocessing issue, but the `with` should be supposed to handle it, shouldn't it?

**Comment by jrapin** [comment]
Hi @franchesoni thank your for the bug report
I could reproduce it in #711. This is due to the progress bar not being picklable. I'm not sure how to fix this for now (it may require adding `__getstate__` and `__setstate__` to the callback if I get it right)
@louismartin you have been using both the progress bar and pickle dump, did you come across this issue and fixed it somehow?

**Comment by louismartin** [comment]
Hi I haven't run into this issue but I am not sure if I used both in combination.

**Comment by jrapin** [comment]
@franchesoni this should be solved on master, please reopen if it's still buggy!
