### ISSUE TITLE
cannot import the library

### ISSUE THREAD

**Issue by mchirsa5** [facebookresearch/nevergrad#763]
## Steps to reproduce

  1. I tried to import the library into the python script but got the error straight away. 
the code and the error is shown below

>>> import nevergrad
Traceback (most recent call last):
  File "<pyshell#9>", line 1, in <module>
    import nevergrad
  File "C:\Users\mchirsa5\AppData\Local\Programs\Python\Python35\lib\site-packages\nevergrad\__init__.py", line 6, in <module>
    from .optimization import optimizerlib as optimizers  # busy namespace, likely to be simplified
  File "C:\Users\mchirsa5\AppData\Local\Programs\Python\Python35\lib\site-packages\nevergrad\optimization\__init__.py", line 6, in <module>
    from .base import Optimizer  # abstract class, for type checking
  File "C:\Users\mchirsa5\AppData\Local\Programs\Python\Python35\lib\site-packages\nevergrad\optimization\base.py", line 36
    assert isinstance(opt, cls), f"You should only load {cls} with this method (found {type(opt)})"
                                                                                                  ^
SyntaxError: invalid syntax

## Expected Results

  * I didn't expect such error as I have just install this library through pip

## Relevant Code

just only 
import nevergrad

**Comment by fmder** [comment]
f-strings ``f"You should only load {cls} with this method (found {type(opt)})"`` (and nevergrad) are Python 3.6+.

**Comment by mchirsa5** [comment]
I see. I have to update my Python to version 3.6 then.

**Comment by jrapin** [comment]
I'll close this but please reopen if it still does not work with Python 3.6 ;)
